title: JTD 24.02.24
description: Just the Docs 24.02.24
theme: just-the-docs

url: https://karolinaga.github.io/JTD24.02.24

aux_links:
  Template Repository: https://github.com/KarolinaGa/JTD24.02.24
